<script lang="ts">
	import { renderQrSvg } from '$lib/client/exchange-runner/index.js';
	import { Button } from '$lib/components/ui/button/index.js';
	import { Input } from '$lib/components/ui/input/index.js';
	import { Skeleton } from '$lib/components/ui/skeleton/index.js';

	let {
		interactionUrl,
		qrSize = 224,
		headerLabel = 'Live · interaction URL'
	}: {
		interactionUrl: string;
		qrSize?: number;
		/**
		 * Label displayed above the QR. Defaults to the VCALM-flavored
		 * "Live · interaction URL"; the runner panel passes
		 * "Live · OID4VCI offer" when the OID4VCI tab is active.
		 */
		headerLabel?: string;
	} = $props();

	let qrSvg = $state<string | null>(null);
	let qrError = $state<string | null>(null);
	let copied = $state(false);
	let copyTimer: ReturnType<typeof setTimeout> | undefined;

	$effect(() => {
		const url = interactionUrl;
		qrSvg = null;
		qrError = null;

		let cancelled = false;
		void renderQrSvg(url, qrSize)
			.then((svg) => {
				if (!cancelled) qrSvg = svg;
			})
			.catch((e: unknown) => {
				if (!cancelled) qrError = e instanceof Error ? e.message : String(e);
			});

		return () => {
			cancelled = true;
		};
	});

	async function copyUrl() {
		try {
			await navigator.clipboard.writeText(interactionUrl);
			copied = true;
			if (copyTimer) clearTimeout(copyTimer);
			copyTimer = setTimeout(() => {
				copied = false;
			}, 1800);
		} catch {
			// Silent — the URL is also visible in the input next to the button.
		}
	}
</script>

<div class="space-y-4 rounded-md border border-live-border bg-live-soft p-5">
	<header class="space-y-1">
		<p class="text-label-md text-live">{headerLabel}</p>
		<p class="text-body-md text-foreground">
			Scan the QR code with the wallet under test, or copy the URL below.
		</p>
	</header>

	<div class="flex justify-center">
		{#if qrSvg}
			<div
				class="rounded-md bg-background p-3 ring-2 ring-live-border"
				style:width="{qrSize + 24}px"
				style:height="{qrSize + 24}px"
				aria-label="Interaction URL QR code"
			>
				<!-- qrSvg is SVG markup generated by the qrcode library from the
					 plain `interactionUrl` string; no user HTML is interpolated. -->
				<!-- eslint-disable-next-line svelte/no-at-html-tags -->
				{@html qrSvg}
			</div>
		{:else if qrError}
			<p class="text-body-md text-destructive">QR unavailable: {qrError}</p>
		{:else}
			<Skeleton class="rounded-md" style="width: {qrSize + 24}px; height: {qrSize + 24}px;" />
		{/if}
	</div>

	<div class="space-y-2">
		<label class="text-label-md text-muted-foreground" for="interaction-url-input"
			>URL (paste into wallet)</label
		>
		<div class="flex items-center gap-2">
			<Input
				id="interaction-url-input"
				readonly
				value={interactionUrl}
				class="font-mono text-body-md"
			/>
			<Button type="button" variant="outline" onclick={copyUrl} aria-live="polite">
				{copied ? 'Copied' : 'Copy'}
			</Button>
		</div>
	</div>
</div>
