name: ler-interoperability-test-suite-dev

services:
  signing-service:
    image: skybridgeskills/dcc-signing-service@sha256:ea486bc5c71f78cb93057fafad95885a1a33fd911aee348faee111283f158050
    container_name: lits-signing-service
    ports:
      - '4006:4006'
    environment:
      PORT: 4006
    volumes:
      - ./.data/signing-service:/data

  transaction-service:
    image: skybridgeskills/dcc-transaction-service@sha256:bdc718e04bec809246429b31ec13ab35f521e5c7bbff211be25f434a06334109
    container_name: lits-transaction-service
    depends_on:
      - signing-service
    ports:
      - '4004:4004'
    environment:
      PORT: 4004
      DEFAULT_EXCHANGE_HOST: ${DEFAULT_EXCHANGE_HOST:-http://localhost:4004}
      SIGNING_SERVICE: http://signing-service:4006
      PERSIST_TO_FILE: /data/exchanges.kv
      TENANT_TOKEN_DEFAULT: ${TENANT_TOKEN_DEFAULT:?must be set in .env}
      ACCESS_JWT_SECRET: ${ACCESS_JWT_SECRET:?must be set in .env}
    volumes:
      - ./.data/transaction-service:/data
